spring:
  jmx:
    enabled: false
#默认启动配置。通过启动参数，激活不同的配置文件，达到服务集群，以及模拟不同服务的目的。
  profiles:
    active: gateway0
  cloud:
    #网关配置。可以通过配置文件方式、java方式配置。
    #https://www.ngui.cc/51cto/show-34038.html
    #https://www.cnblogs.com/chinaWu/p/12731796.html    gateway:      discovery:        locator:
        #启用网关集成，利用微服务名称进行路由          enabled: true
          #服务id转换为小写，默认的eureka注册中心里注册的服务名称是大写的，无法匹配到服务。
          #如果不配置，路由配置中的uri用lb://服务名，大小写要和注册中心一样。如lb://producer改为lb://PRODUCER
          lower-case-service-id: true
      routes:
      #路由id，无规定规则，但要求唯一，建议配合服务名      - id: producer
      #匹配成功后的路由地址。可以是实际地址，也可以是微服务名。lb代表通过服务名称进行负载均衡，http不会。
#       uri: http://localhost:8070
        uri: lb://producer
        #断言，路由匹配规则，可以有多种匹配规则。匹配规则可以通过路径、cookie、请求头、时间等。
        predicates:        - Path=/producer/**
      
      - id: consumer
        uri: lb://consumer
        predicates:
        - Path=/consumer/**

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 120
    lease-renewal-interval-in-seconds: 40
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka,http://eureka1:8091/eureka,http://eureka2:8092/eureka
