eureka:
  server:
#自我保护机制，防止网络注册服务中心，因网络不好，某段时间统计心跳失败太多，而误清除实际存活的服务模块。
#但这样也会拿到实际已经不存在的服务模块，所以客户端要有容错机制，如重试，断路器等。
#自己设置是否需要自我保护机制，默认为true。
#开发环境不需要，而且客户端没有此功能。
#此配置文件加载优先级没有bootstrap.yml、application.properties文件高，如果这些主文件有重复属性应该会被覆盖。
    enable-self-preservation: false